### ISSUE TITLE
Callback not found

### ISSUE THREAD

**Issue by apolkingg8** [aroth/react-native-uploader#1]
Sometimes I got callback error when I use `for-loop` with `RNUploader.upload()` (because I need each file has their own progress). 
Error msg like that: `Invariant Violation: Callback with id 343: RNUploader.upload() not found`. 

BTW, thanks for this cool plugin! :beer:

**Comment by aroth** [comment]
You're welcome. I'll take a look at this and report back.

**Comment by aroth** [comment]
@demiurga can you give me an example of how you're looping over files and calling RNUploader.upload()? The module wasn't specifically designed to handle that use case, but I'll see what's possible.

**Comment by apolkingg8** [comment]
For example:

``` js
opts.forEach((opt)=> {
  RNUploader.upload(opt, (err, res)=> {
    // ...something in callback
  })
})
```

**Comment by aroth** [comment]
@demiurga I toyed with a few ideas, but calling `RNUploader.upload(...)` in a loop is not supported at this time. Due to the way native modules are loaded (and certain implementation details of react-native-uploader itself), each `upload(...)` call will overwrite instance variables including the stored callback. 

If I am able to add this feature in the future I will let you know.

**Comment by apolkingg8** [comment]
Got it, I resolved this issue with a promise waterfall. Thank you!
